upstream vnc_proxy {
    server websockify;
}

upstream vnc_client {
    server novnc:6080;
}	 

server {
    listen 80; # consider using 443, see below
    server_name localhost;
    root /srv/www;
    

    location /websockify {
    # location / {
	  proxy_http_version 1.1;
 	  proxy_pass http://vnc_proxy/;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

	  proxy_read_timeout 61s;
	  proxy_buffering off;

 
    }

    location /vncws {
            # add_header Cache-Control no-cache;
            index vnc.html;
	    alias /srv/www/noVNC;
            try_files $uri $uri/ /vnc.html;

    }

}
